// ── App Stage ─────────────────────────────────────────────────────────────────
// Generates .vue component files from IR component trees.

import type { Stage, StageInput, StageOutput, OutputFile, IR, IRComponent } from "../../ir"
import { renderNode } from "./template"
import { renderScript } from "./script"

export const appStage: Stage = {
  name: "app",

  async handle({ ir }: StageInput): Promise<StageOutput> {
    const files: OutputFile[] = []

    for (const comp of ir.components) {
      files.push({
        path: `src/components/${comp.name}.vue`,
        content: generateVueComponent(comp, ir),
      })
    }

    files.push({
      path: "src/components/registry.ts",
      content: generateRegistry(ir),
    })

    files.push({
      path: ".gitignore",
      content: `node_modules\ndist\n.DS_Store\n*.local\n`,
    })

    return { files, deps: [] }
  },
}

function generateVueComponent(comp: IRComponent, ir: IR): string {
  const { template, handlers } = renderNode(comp.tree, "  ", ir, comp.name)
  const script = renderScript(comp, ir, handlers)

  return `<script setup lang="ts">
${script}
</script>

<template>
${template}
</template>
`
}

function generateRegistry(ir: IR): string {
  const nuxtUI: string[] = []
  const vueRouter: string[] = []
  const vueBuiltIn: string[] = []
  const custom: string[] = []

  for (const name of ir.usedComponents) {
    if (name.startsWith("U")) {
      nuxtUI.push(name)
    } else if (name === "RouterLink" || name === "RouterView") {
      vueRouter.push(name)
    } else if (name === "Teleport" || name === "Transition") {
      vueBuiltIn.push(name)
    } else {
      custom.push(name)
    }
  }

  const imports: string[] = []

  if (nuxtUI.length > 0) {
    imports.push(`import { ${nuxtUI.join(", ")} } from "@nuxt/ui"`)
  }

  if (vueRouter.length > 0) {
    imports.push(`import { ${vueRouter.join(", ")} } from "vue-router"`)
  }

  if (vueBuiltIn.length > 0) {
    imports.push(`import { ${vueBuiltIn.join(", ")} } from "vue"`)
  }

  for (const name of custom) {
    imports.push(`import ${name} from "@/components/${name}.vue"`)
  }

  const registryEntries: string[] = []
  for (const name of [...vueBuiltIn, ...vueRouter, ...nuxtUI, ...custom]) {
    registryEntries.push(`  ${name},`)
  }

  return `// Generated by edem-codegen — do not edit manually
${imports.join("\n")}

export const registry = {
${registryEntries.join("\n")}
}
`
}
