export const dataManifest = {
  collections: [
    {
      id: "projects",
      fields: [
        { name: "name", type: "string", required: true },
        { name: "slug", type: "string", required: true },
        { name: "description", type: "text" },
        { name: "icon", type: "string" },
        { name: "logo", type: "image" },
        { name: "type", type: "string", default: "desktop" },
        { name: "sort_order", type: "number", default: 0 },
      ],
    },
    {
      id: "ideas",
      fields: [
        { name: "project_id", type: "uuid", required: true },
        { name: "title", type: "string", required: true },
        { name: "description", type: "text" },
        { name: "level", type: "string" },
        { name: "type", type: "string" },
        { name: "status", type: "string", default: "draft" },
      ],
    },
    {
      id: "project_flows",
      fields: [
        { name: "project_id", type: "uuid", required: true },
        { name: "name", type: "string", required: true },
        { name: "status", type: "string", default: "draft" },
        { name: "kind", type: "string", default: "flow" },
        { name: "nodes", type: "json" },
        { name: "edges", type: "json" },
        { name: "valid", type: "boolean", default: true },
        { name: "validation_errors", type: "json" },
        { name: "meta", type: "json" },
        { name: "manifest_id", type: "string" },
        { name: "backpressure", type: "json" },
      ],
    },
    {
      id: "project_data_collections",
      fields: [
        { name: "project_id", type: "uuid", required: true },
        { name: "manifest_id", type: "string", required: true },
        { name: "name", type: "string", required: true },
        { name: "singleton", type: "boolean", default: false },
        { name: "fields", type: "json" },
        { name: "labels", type: "json" },
        { name: "description", type: "text" },
        { name: "icon", type: "string" },
      ],
    },
    {
      id: "project_ui_components",
      fields: [
        { name: "project_id", type: "uuid", required: true },
        { name: "manifest_id", type: "string", required: true },
        { name: "name", type: "string", required: true },
        { name: "tree", type: "json" },
      ],
    },
    {
      id: "project_ui_routes",
      fields: [
        { name: "project_id", type: "uuid", required: true },
        { name: "manifest_id", type: "string", required: true },
        { name: "path", type: "string", required: true },
        { name: "root", type: "string" },
        { name: "redirect", type: "string" },
        { name: "parent_manifest_id", type: "string" },
        { name: "sort_order", type: "number", default: 0 },
      ],
    },
    {
      id: "flows",
      fields: [
        { name: "project_id", type: "uuid" },
        { name: "name", type: "string", required: true },
        { name: "status", type: "string", default: "draft" },
        { name: "kind", type: "string", default: "flow" },
        { name: "nodes", type: "json" },
        { name: "edges", type: "json" },
        { name: "valid", type: "boolean", default: true },
        { name: "validation_errors", type: "json" },
        { name: "meta", type: "json" },
        { name: "manifest_id", type: "string" },
        { name: "backpressure", type: "json" },
      ],
    },
    {
      id: "logs",
      fields: [
        { name: "level", type: "string", required: true },
        { name: "message", type: "text", required: true },
        { name: "source", type: "string", required: true },
        { name: "args", type: "json" },
        { name: "count", type: "number" },
      ],
    },
    {
      id: "app_state",
      singleton: true,
      fields: [
        { name: "last_route", type: "json" },
        { name: "locale", type: "string" },
        {
          name: "locales",
          type: "json",
          default: [
            { value: "en", label: "English", flag: "🇺🇸" },
            { value: "ru", label: "Русский", flag: "🇷🇺" },
          ],
        },
        { name: "dark", type: "boolean", default: false },
        { name: "window_frame", type: "json" },
        { name: "window_maximized", type: "boolean", default: false },
      ],
    },
    {
      id: "agent_providers",
      fields: [
        { name: "name", type: "string", required: true },
        { name: "api_url", type: "string", required: true },
        { name: "api_key", type: "string" },
        { name: "models", type: "json" },
        { name: "active_model", type: "string" },
      ],
    },
    {
      id: "agent_settings",
      singleton: true,
      fields: [
        { name: "active_provider_id", type: "string" },
        { name: "voice", type: "string" },
        { name: "language", type: "string", default: "auto" },
        { name: "auto_listen", type: "boolean", default: false },
        { name: "volume", type: "number", default: 0.8 },
        { name: "tts_voice", type: "string" },
        { name: "tts_speed", type: "number", default: 1.0 },
      ],
    },
    {
      id: "agent_conversation",
      singleton: true,
      fields: [{ name: "messages", type: "json", default: [] }],
    },
  ],
} as const
