// Generated by edem-codegen — do not edit manually
import {
  UBadge,
  UButton,
  UIcon,
  UInput,
  UScrollArea,
  USelect,
  USkeleton,
  USwitch,
  UTextarea,
  UTooltip,
} from "@nuxt/ui"
import { RouterLink } from "vue-router"
import DebugFlowRuns from "@/components/DebugFlowRuns.vue"
import DebugLogs from "@/components/DebugLogs.vue"
import FlowEditorPage from "@/components/FlowEditorPage.vue"
import LogoSvg from "@/components/LogoSvg.vue"
import MenuLayout from "@/components/MenuLayout.vue"
import ProjectsSidebar from "@/components/ProjectsSidebar.vue"
import SettingsLayout from "@/components/SettingsLayout.vue"

export const registry = {
  RouterLink,
  UBadge,
  UButton,
  UIcon,
  UInput,
  UScrollArea,
  USelect,
  USkeleton,
  USwitch,
  UTextarea,
  UTooltip,
  DebugFlowRuns,
  DebugLogs,
  FlowEditorPage,
  LogoSvg,
  MenuLayout,
  ProjectsSidebar,
  SettingsLayout,
}
