// Generated by edem-codegen — do not edit manually
import {
  UBadge,
  UButton,
  UIcon,
  UInput,
  UScrollArea,
  USelect,
  USelectMenu,
  USwitch,
  UTextarea,
  UTooltip,
} from "@nuxt/ui"
import { RouterLink } from "vue-router"
import LogoSvg from "@/components/LogoSvg.vue"
import MenuLayout from "@/components/MenuLayout.vue"
import NodeConfigPanel from "@/components/NodeConfigPanel.vue"
import ProjectsSidebar from "@/components/ProjectsSidebar.vue"
import SettingsLayout from "@/components/SettingsLayout.vue"
import VueFlow from "@/components/VueFlow.vue"

export const registry = {
  RouterLink,
  UBadge,
  UButton,
  UIcon,
  UInput,
  UScrollArea,
  USelect,
  USelectMenu,
  USwitch,
  UTextarea,
  UTooltip,
  LogoSvg,
  MenuLayout,
  NodeConfigPanel,
  ProjectsSidebar,
  SettingsLayout,
  VueFlow,
}
