import type { Stage, StageInput, StageOutput } from "../ir"

// ── Bun Stage ─────────────────────────────────────────────────────────────────
// Creates output directory and generates bunfig.toml.
// package.json is generated by the module from collected stage deps/scripts.

export const bunStage: Stage = {
  name: "bun",

  async handle({ output }: StageInput): Promise<StageOutput> {
    const { mkdirSync, writeFileSync } = await import("fs")

    mkdirSync(output, { recursive: true })

    writeFileSync(
      `${output}/bunfig.toml`,
      `[install]\nsaveTextLockfile = true\nexact = true\n`,
      "utf-8",
    )

    return { files: [], deps: [] }
  },
}
